theme: jekyll-theme-so-simple
#remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
logo: # path of site logo
title: wd4rnr - Radio in the Wild
description: "The ruminations of an amateur radio operator... a Ham"
baseurl: # "/wd4rnr" # the subpath of your site, e.g. /blog
url: "https://r3dact3d.github.io" # the base hostname & protocol for your site, e.g. http://example.com

date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200
mathjax:
  enable: # MathJax equations, e.g. true, false (default)
  combo:  # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    
#about-author: Consulting architect and Linux engineer by trade, but also very passionate about the outdoors and promoting the art of amateur radio.

# Disqus
disqus:
  shortname: radio-in-the-wild # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/
twitter:
  username: RedactedTech

# Tracker
google_analytics: # UA-NNNNNNNNN-N

# Paginate
#paginate: 12
#paginate_path: /page:num/

search_full_content: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: "Brady Thompson"
  picture:
  email: "redhatbrady@gmail.com"
  twitter: RedactedTech
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
