locale: en-US
logo: #"/images/me.png" # path of site logo
title: w5aww
description: "The ruminations of an amateur radio operator"
baseurl: # "/w5aww" # the subpath of your site, e.g. /blog
url: "https://r3dact3d.github.io" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-primer

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  enabled:          true

repository: hikerpig/foam-jekyll-template

# Generate permalinks in format specified in: https://jekyllrb.com/docs/permalinks/#built-in-formats
permalink: pretty

plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
