remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/default.css"
locale: en-US
logo: #"/images/me.png" # path of site logo
title: w5aww
description: "The ruminations of an amateur radio operator"
baseurl: # "/w5aww" # the subpath of your site, e.g. /blog
url: "https://r3dact3d.github.io" # the base hostname & protocol for your site, e.g. http://example.com

date_format: "%B %-d, %Y"
read_time: true # reading time estimates, e.g. true
words_per_minute: # 200
markdown: kramdown
mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo:  "tex-svg" # "tex-svg" (default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
  tags:  ams # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
    
#about-author: Consulting architect and Linux engineer by trade, but also very passionate about the outdoors and promoting the art of amateur radio.

# Disqus
disqus:
  shortname: radio-in-the-wild # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/
twitter:
  username: RedactedTech

# Tracker
google_analytics: # UA-NNNNNNNNN-N

# Paginate
paginate: 12
paginate_path: /page:num/

search_full_content: false

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true

# Site Author
author:
  name: "Brady Thompson"
  picture: "/images/face.jpg"
  email: "redhatbrady@gmail.com"
  twitter: RedactedTech
  links:
    - title: Twitter
      url: https://twitter.com/RedactedTech
      icon: fab fa-twitter-square

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
